include::page$attributes.adoc[]
[[spring-cloud-zookeeper-dependency-watcher-presence-checker]]
=== Using the Presence Checker

Bound with the Dependency Watcher is the functionality called Presence Checker. It lets
you provide custom behavior when your application boots, to react according to the state
of your dependencies.

The default implementation of the abstract
`org.springframework.cloud.zookeeper.discovery.watcher.presence.DependencyPresenceOnStartupVerifier`
class is the
`org.springframework.cloud.zookeeper.discovery.watcher.presence.DefaultDependencyPresenceOnStartupVerifier`,
which works in the following way.

. If the dependency is marked us `required` and is not in Zookeeper, when your application
boots, it throws an exception and shuts down.
. If the dependency is not `required`, the
`org.springframework.cloud.zookeeper.discovery.watcher.presence.LogMissingDependencyChecker`
logs that the dependency is missing at the `WARN` level.

Because the `DefaultDependencyPresenceOnStartupVerifier` is registered only when there is
no bean of type `DependencyPresenceOnStartupVerifier`, this functionality can be
overridden.

