include::page$attributes.adoc[]

=== Management Endpoints

By default, if you use `@EnableZuulProxy` with the Spring Boot Actuator, you enable two additional endpoints:

* Routes
* Filters

==== Routes Endpoint

A GET to the routes endpoint at `/routes` returns a list of the mapped routes:

.GET /routes
[source,json]
----
{
  /stores/**: "http://localhost:8081"
}
----

Additional route details can be requested by adding the `?format=details` query string to `/routes`.
Doing so produces the following output:

.GET /routes/details
[source,json]
----
{
  "/stores/**": {
    "id": "stores",
    "fullPath": "/stores/**",
    "location": "http://localhost:8081",
    "path": "/**",
    "prefix": "/stores",
    "retryable": false,
    "customSensitiveHeaders": false,
    "prefixStripped": true
  }
}
----

A `POST` to `/routes` forces a refresh of the existing routes (for example, when there have been changes in the service catalog).
You can disable this endpoint by setting `endpoints.routes.enabled` to `false`.

NOTE: the routes should respond automatically to changes in the service catalog, but the `POST` to `/routes` is a way to force the change
to happen immediately.

==== Filters Endpoint

A `GET` to the filters endpoint at `/filters` returns a map of Zuul filters by type.
For each filter type in the map, you get a list of all the filters of that type, along with their details.
