include::page$attributes.adoc[]

=== Strangulation Patterns and Local Forwards

A common pattern when migrating an existing application or API is to "`strangle`" old endpoints, slowly replacing them with different implementations.
The Zuul proxy is a useful tool for this because you can use it to handle all traffic from the clients of the old endpoints but redirect some of the requests to new ones.

The following example shows the configuration details for a "`strangle`" scenario:

.application.yml
[source,yaml]
----
 zuul:
  routes:
    first:
      path: /first/**
      url: https://first.example.com
    second:
      path: /second/**
      url: forward:/second
    third:
      path: /third/**
      url: forward:/3rd
    legacy:
      path: /**
      url: https://legacy.example.com
----

In the preceding example, we are strangle the "`legacy`" application, which is mapped to all requests that do not match one of the other patterns.
Paths in `/first/{all}` have been extracted into a new service with an external URL.
Paths in `/second/{all}` are forwarded so that they can be handled locally (for example, with a normal Spring `@RequestMapping`).
Paths in `/third/{all}` are also forwarded but with a different prefix (`/third/foo` is forwarded to `/3rd/foo`).

NOTE: The ignored patterns aren't completely ignored, they just are not handled by the proxy (so they are also effectively forwarded locally).
