include::page$attributes.adoc[]

=== Access Control Lists (ACLs)

You can add authentication information for Zookeeper ACLs by calling the `addAuthInfo`
method of a `CuratorFramework` bean. One way to accomplish this is to provide your own
`CuratorFramework` bean, as shown in the following example:

[source,java,indent=0]
----
@BoostrapConfiguration
public class CustomCuratorFrameworkConfig {

  @Bean
  public CuratorFramework curatorFramework() {
    CuratorFramework curator = new CuratorFramework();
    curator.addAuthInfo("digest", "user:password".getBytes());
    return curator;
  }

}
----
Consult
https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-core/src/main/java/org/springframework/cloud/zookeeper/ZookeeperAutoConfiguration.java[the ZookeeperAutoConfiguration class]
to see how the `CuratorFramework` bean's default configuration.

Alternatively, you can add your credentials from a class that depends on the existing
`CuratorFramework` bean, as shown in the following example:

[source,java,indent=0]
----
@BoostrapConfiguration
public class DefaultCuratorFrameworkConfig {

  public ZookeeperConfig(CuratorFramework curator) {
    curator.addAuthInfo("digest", "user:password".getBytes());
  }

}
----

The creation of this bean must occur during the boostrapping phase. You can register
configuration classes to run during this phase by annotating them with
`@BootstrapConfiguration` and including them in a comma-separated list that you set as the
value of the `org.springframework.cloud.bootstrap.BootstrapConfiguration` property in the
`resources/META-INF/spring.factories` file, as shown in the following example:

.resources/META-INF/spring.factories
----
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
my.project.CustomCuratorFrameworkConfig,\
my.project.DefaultCuratorFrameworkConfig
----

