include::page$attributes.adoc[]
[[spring-cloud-zookeeper-config]]
== Distributed Configuration with Zookeeper

Zookeeper provides a
https://zookeeper.apache.org/doc/current/zookeeperOver.html#sc_dataModelNameSpace[hierarchical namespace]
that lets clients store arbitrary data, such as configuration data. Spring Cloud Zookeeper
Config is an alternative to the
https://github.com/spring-cloud/spring-cloud-config[Config Server and Client].
Configuration is loaded into the Spring Environment during the special "`bootstrap`"
phase. Configuration is stored in the `/config` namespace by default. Multiple
`PropertySource` instances are created, based on the application's name and the active
profiles, to mimic the Spring Cloud Config order of resolving properties. For example, an
application with a name of `testApp` and with the `dev` profile has the following property
sources created for it:

* `config/testApp,dev`
* `config/testApp`
* `config/application,dev`
* `config/application`

The most specific property source is at the top, with the least specific at the bottom.
Properties in the `config/application` namespace apply to all applications that use
zookeeper for configuration. Properties in the `config/testApp` namespace are available
only to the instances of the service named `testApp`.

Configuration is currently read on startup of the application. Sending a HTTP `POST`
request to `/refresh` causes the configuration to be reloaded. Watching the configuration
namespace (which Zookeeper supports) is not currently implemented.
